### ISSUE TITLE
Tab key changes focus instead of indenting.

### ISSUE THREAD

**Issue by travm** [symphonycms/markdown#7]
I hope I'm submitting this in the correct place. As I use Symphony more and more, I've been running into a lot of trouble with indenting for code blocks in Symphony.

Instead of indenting, the tab key will just change input focus on the page. (Which may be intentional. Accessibility?) But, when writing content with many code blocks it can be quite cumbersome to space indent every single line.

**Comment by michael-e** [comment]
I see what you mean, but changing the browsers behaviour to insert a tab character instead of changing the focus should be the task of a different extension, IMHO. It has nothing to do with Markdown.

**Comment by nitriques** [comment]
> IMHO. It has nothing to do with Markdown.

Absolutely nothing. Please consider using a text editor in order to get the wanted behavior.

I can say that [editor_for_symphony](https://github.com/symphonists/editor_for_symphony) works great and has tab support.

If not, something like codemirror would also work.

I am closing this issue since it is not related to the current project.
